(() => {
  "use strict";
  const root = document.documentElement;
  const readStorage = (key, fallback) => { try { return localStorage.getItem(key) || fallback; } catch { return fallback; } };
  const writeStorage = (key, value) => { try { localStorage.setItem(key, value); } catch { /* Storage can be disabled. */ } };
  const language = readStorage("portfolio-language", "en") === "tr" ? "tr" : "en";
  const themeButton = document.querySelector("[data-theme-toggle]");
  const languageButton = document.querySelector("[data-language-toggle]");
  const menuButton = document.querySelector("[data-menu]");
  const nav = document.querySelector(".nav");
  const themeColor = document.querySelector("[data-theme-color]");
  const tr = {
    "meta.homeTitle":"Barış Sürkit — Yazılım, Yapay Zekâ ve Veri", "meta.homeDescription":"Barış Sürkit, yapay zekâ, veri ve modern web teknolojileriyle yazılım geliştiriyor.", "meta.projectsTitle":"Projeler — Barış Sürkit", "meta.projectsDescription":"Barış Sürkit'in seçili yazılım, yapay zekâ ve veri projeleri.", "meta.caseTitle":"AI Search Engine — Vaka Çalışması", "meta.caseDescription":"AI Search Engine: kaynakları incelenebilir kılan araştırma çalışma alanı vaka çalışması.", "meta.devlensTitle":"DevLens — Vaka Çalışması", "meta.devlensDescription":"DevLens: herkese açık GitHub kanıtlarıyla portfolyo sinyallerini analiz eden full-stack uygulama.", "meta.404Title":"Sayfa bulunamadı — Barış Sürkit",
    "nav.about":"Hakkımda", "nav.journey":"Yolculuk", "nav.projects":"Projeler", "nav.stack":"Teknolojiler", "nav.allProjects":"Tüm işler", "nav.contact":"İletişim",
    "hero.role":"Bilgisayar Mühendisliği Öğrencisi", "hero.intro":"Yapay zekâ, veri ve modern web teknolojileri üzerine uygulamalı projeler geliştiriyorum.", "hero.education":"Trakya Üniversitesi · Bilgisayar Mühendisliği",
    "featured.label":"01 / ÖNE ÇIKAN ÇALIŞMA", "featured.intro":"Canlı web ve seçili belgeler üzerinde araştırma yapmayı sağlayan, kaynak odaklı bir çalışma alanı.", "featured.description":"Yanıtların dayandığı kaynakları incelemeyi kolaylaştıran bu proje; streaming yanıtları, devam sorularını ve Web, Dosyalar ile Hibrit araştırma modlarını bir araya getiriyor.", "featured.case":"Vaka çalışmasını oku →", "featured.demo":"Canlı demo ↗", "ai.one":"Canlı web ve seçili belgelerde retrieval", "ai.two":"Her mesaja ait kaynaklar ve ayrı bir kaynak paneli", "ai.three":"Tarayıcıda saklanan geçmiş ve SSE ile streaming yanıtlar",
    "other.label":"02 / DİĞER ÇALIŞMALAR", "other.title":"Diğer projeler", "other.link":"Tüm projeleri gör →", "budget.copy":"Gelir ve giderleri kategorilere ayırarak takip etmeyi sağlayan full-stack kişisel bütçe uygulaması.", "portfolio.title":"Kişisel Portfolyo", "portfolio.copy":"Projelerimi ve mühendislik çalışmalarımı paylaştığım erişilebilir, iki dilli portfolyo sitesi.",
    "about.label":"03 / HAKKIMDA", "about.title":"Hakkımda", "about.copy":"Trakya Üniversitesi Bilgisayar Mühendisliği öğrencisiyim. Veri analizinden full-stack uygulamalara ve yapay zekâ destekli araştırma araçlarına kadar farklı alanlarda projeler geliştirerek öğreniyorum.", "about.cvEn":"CV (EN) ↓", "about.cvTr":"CV (TR) ↓",
    "journey.label":"04 / YOLCULUK", "journey.title":"Deneyim ve eğitim", "journey.eduTitle":"Bilgisayar Mühendisliği Lisans", "journey.eduCopy":"Trakya Üniversitesi · Eğitim devam ediyor", "journey.internDate":"Ağustos 2026", "journey.internTitle":"Yazılım Stajyeri",
    "stack.label":"05 / TEKNOLOJİLER", "stack.title":"Kullandığım teknolojiler", "stack.lang":"Diller", "stack.frontend":"Frontend", "stack.backend":"Backend ve API'ler", "stack.ai":"Yapay Zekâ ve Veri", "stack.retrieval":"Veri / Retrieval", "stack.tools":"Araçlar ve Deployment",
    "contact.label":"06 / İLETİŞİM", "contact.title":"İletişime geçelim.", "contact.copy":"Yazılım, yapay zekâ ve birlikte üretme fırsatları hakkında konuşmak için bana ulaşabilirsiniz.", "contact.email":"E-posta ↗", "footer.role":"Yazılım · Yapay Zekâ · Veri", "footer.top":"Başa dön ↑", "footer.home":"Ana sayfaya dön ↑",
    "projects.kicker":"PROJELER", "projects.title":"Projeler", "projects.intro":"Yazılım, yapay zekâ ve veri alanlarından seçili projeler.", "projects.featured":"ÖNE ÇIKAN / YAPAY ZEKÂ", "projects.description":"Canlı web aramasını, seçili belgelerde retrieval'ı ve hibrit RAG yaklaşımını bir araya getiren kaynak odaklı araştırma uygulaması.", "projects.case":"Vaka çalışması →", "projects.live":"Canlı demo ↗", "projects.source":"Kaynak kodu ↗", "projects.budgetLabel":"WEB UYGULAMASI", "projects.budgetDescription":"Next.js, TypeScript, Prisma ve SQLite ile geliştirilen full-stack kişisel bütçe takip uygulaması.", "projects.portfolioLabel":"WEB TASARIMI VE GELİŞTİRME", "projects.portfolioDescription":"Projeleri ve mühendislik çalışmalarını öne çıkaran erişilebilir, iki dilli portfolyo.", "projects.devlensLabel":"GELİŞTİRİCİ ARAÇLARI", "projects.devlensDescription":"Deterministik GitHub kanıtlarıyla portfolyo sinyallerini analiz eden ve isteğe bağlı Gemini yorumlaması sunan full-stack uygulama.",
    "case.kicker":"VAKA ÇALIŞMASI / YAPAY ZEKÂ ARAŞTIRMASI", "case.lede":"Canlı web ve seçili belgelerde araştırma yapmayı, ardından her yanıtın dayandığı kaynakları incelemeyi sağlayan kaynak odaklı bir çalışma alanı.", "case.overview":"GENEL BAKIŞ", "case.overviewTitle":"Araştırma ve kaynaklar aynı yerde.", "case.overviewCopy":"AI Search Engine, Tavily üzerinden canlı web retrieval ile seçili PDF, TXT, Markdown ve DOCX belgelerini tek bir konuşmada birleştiriyor. Yanıtlar aşamalı olarak stream edilirken her mesajın kaynak listesi korunuyor.", "case.arch":"MİMARİ", "case.archTitle":"Tek yanıt modeli, iki farklı kanıt yaşam döngüsü.", "case.frontend":"Frontend", "case.frontendCopy":"React/Vite; çalışma alanını, IndexedDB'de tutulan yerel geçmişi, deep linkleri ve streaming render sürecini yönetiyor.", "case.backend":"Backend", "case.backendCopy":"FastAPI; arama, yanıt üretimi, streaming, belge yükleme, silme ve orkestrasyon işlemlerini yönetiyor.", "case.web":"Web kanıtı", "case.webCopy":"Tavily araması → fetch/extract → chunk → istek kapsamlı Qdrant retrieval → cleanup.", "case.file":"Dosya kanıtı", "case.fileCopy":"Seçili konuşma belgeleri çıkarılır, kalıcı olarak indekslenir ve yalnızca ilgili kapsam içinde retrieve edilir.", "case.generation":"Üretim", "case.generationCopy":"Kaynakları içeren context, Ollama sağlayıcısına aktarılır; yanıt ve kaynaklar birlikte döner.", "case.sources":"Kaynak çalışma alanı", "case.sourcesCopy":"Her mesaja ait Web ve Dosya kaynakları masaüstünde panel, mobilde drawer üzerinden incelenebilir.", "case.decisions":"TEKNİK KARARLAR", "case.scoped":"Kapsam kontrollü retrieval", "case.scopedCopy":"Web kaynakları her istek için geçicidir; belge chunk'ları ise cleanup yapılana kadar seçili konuşmaya bağlı kalır.", "case.citations":"Arayüzün parçası olan citation'lar", "case.citationsCopy":"Metin içindeki citation işaretleri korunmuş kaynak listelerine bağlanarak dayanakları incelemeyi kolaylaştırır.", "case.streaming":"Varsayılan olarak streaming", "case.streamingCopy":"POST + fetch ve ReadableStream üzerinden SSE parsing kullanılarak ilerleme bilgisi ve yanıt parçaları geldikçe render edilir.", "case.evaluation":"Dürüst değerlendirme", "case.evaluationCopy":"Deterministik offline quality gate 29/29 PASS sonucunu veriyor. Citation metrikleri olgusal doğruluk iddiası değil, yapısal regresyon kontrolüdür.", "case.try":"CANLI SÜRÜM", "case.tryTitle":"Uygulamayı inceleyin.", "case.tryCopy":"Production ortamında frontend Vercel'de, FastAPI backend ise Render'da çalışıyor. Ücretsiz backend, bir süre kullanılmadığında geç açılabilir.", "case.open":"Canlı demoyu aç ↗", "case.all":"Tüm projeler ↑",
    "devlens.kicker":"VAKA ÇALIŞMASI / GELİŞTİRİCİ ARAÇLARI", "devlens.lede":"GitHub'daki herkese açık portfolyo sinyallerini deterministik kanıtlarla analiz eden ve isteğe bağlı yapay zekâ yorumlaması sunan full-stack bir uygulama.", "devlens.overview":"GENEL BAKIŞ", "devlens.overviewTitle":"Kanıt önce, yorum sonra.", "devlens.overviewCopy":"DevLens; README dosyaları, proje yapısı, manifestolar, testler, CI ve lisans gibi gözlemlenebilir sinyalleri bir araya getirir. Skorlar deterministik analizden gelir; Gemini yalnızca açıklama ve sonraki proje önerisi için isteğe bağlı bir katman olarak çalışır.", "devlens.arch":"MİMARİ", "devlens.archTitle":"Deterministik analiz bağımsız kalır.", "devlens.archCopy":"Next.js ve React frontend, FastAPI backend, PostgreSQL snapshot cache ve GitHub API sınırlarıyla ayrılır. Sınırlı eşzamanlılık, TTL ve engine-version kontrolleri ile sonuçların davranışı ölçülebilir tutulur.", "devlens.reliability":"GÜVENİLİRLİK", "devlens.reliabilityTitle":"Kısmi başarıyı ve sınırları görünür kılmak.", "devlens.reliabilityCopy":"Gemini kullanılamadığında deterministik analiz geçerliliğini korur. Backend; request ID'leri, yapılandırılmış loglar ve sağlayıcı hata sınıflarıyla gözlemlenebilirlik sağlar; sistem yalnızca herkese açık GitHub verilerini analiz eder.", "devlens.open":"Canlı demoyu aç ↗", "devlens.source":"Kaynak kodu ↗",
    "notfound.kicker":"404 / BULUNAMADI", "notfound.title":"Bu sayfa bulunamadı.", "notfound.copy":"Aradığınız sayfa kaldırılmış veya başka bir adrese taşınmış olabilir.", "notfound.back":"Ana sayfaya dön →", "alt.ai":"Yanıtı, citation'ları ve kaynakları gösteren AI Search Engine çalışma alanı", "alt.budget":"BütçeDostum kişisel bütçe uygulaması ekranı", "alt.portfolio":"Barış Sürkit kişisel portfolyo sitesi"
  };
  const applyLanguage = () => {
    const isTurkish = language === "tr";
    root.lang = language;
    document.querySelectorAll("[data-i18n]").forEach((el) => { if (isTurkish && tr[el.dataset.i18n]) el.textContent = tr[el.dataset.i18n]; });
    document.querySelectorAll("[data-i18n-content]").forEach((el) => { if (isTurkish && tr[el.dataset.i18nContent]) el.content = tr[el.dataset.i18nContent]; });
    document.querySelectorAll("[data-i18n-alt]").forEach((el) => { if (isTurkish && tr[el.dataset.i18nAlt]) el.alt = tr[el.dataset.i18nAlt]; });
    const titleKey = document.querySelector("title[data-i18n]")?.dataset.i18n;
    if (isTurkish && titleKey && tr[titleKey]) document.title = tr[titleKey];
    if (isTurkish && document.querySelector("title[data-page-title='meta.title']")) document.title = tr["meta.homeTitle"];
    if (nav) nav.setAttribute("aria-label", isTurkish ? "Ana navigasyon" : "Main navigation");
    if (menuButton) menuButton.textContent = isTurkish ? "Menü" : "Menu";
    const skip = document.querySelector(".skip-link"); if (skip) skip.textContent = isTurkish ? "İçeriğe geç" : "Skip to content";
    const isDark = root.dataset.theme === "dark";
    if (themeButton) themeButton.setAttribute("aria-label", isTurkish ? (isDark ? "Açık temaya geç" : "Koyu temaya geç") : (isDark ? "Switch to light theme" : "Switch to dark theme"));
    const themeIcon = document.querySelector("[data-theme-icon]"); if (themeIcon) themeIcon.textContent = isDark ? "☀" : "☾";
    if (languageButton) { languageButton.textContent = isTurkish ? "EN" : "TR"; languageButton.lang = isTurkish ? "en" : "tr"; languageButton.setAttribute("aria-label", isTurkish ? "Switch to English" : "Switch to Turkish"); }
  };
  themeButton?.addEventListener("click", () => { const theme = root.dataset.theme === "dark" ? "light" : "dark"; root.dataset.theme = theme; writeStorage("portfolio-theme", theme); if (themeColor) themeColor.content = theme === "dark" ? "#101419" : "#f7f8f9"; applyLanguage(); });
  languageButton?.addEventListener("click", () => { writeStorage("portfolio-language", language === "en" ? "tr" : "en"); location.reload(); });
  menuButton?.addEventListener("click", () => { const open = nav?.classList.toggle("open") || false; menuButton.setAttribute("aria-expanded", String(open)); });
  nav?.querySelectorAll("a").forEach((link) => link.addEventListener("click", () => { nav.classList.remove("open"); menuButton?.setAttribute("aria-expanded", "false"); }));
  applyLanguage();
})();
